### ISSUE TITLE
Best computer parts for ray?

### ISSUE THREAD

**Issue by ghost** [zakki/Ray#108]
What are the best parts to get to run ray? I know GPU probably matters a lot, but what about CPU and RAM and other things?

**Comment by jeroeness** [comment]
Hey @Azirine , 

I just checked this repo, very interesting! For the hardware part you probably want to focus on fast processor. GPU doesn't matter in your code because you don't use any hardware acceleration (from what I saw). You can drop out the GPU and focus on the CPU, I would suggest taking a look at the brand new AMD Ryzen https://www.amd.com/en/products/cpu/amd-ryzen-7-1700 . The performance/price ratio is very good compared to the Intel-i9. The strength in the AMD Ryzen (and also the Intel-i9) is the amount of threads they have. Ryzen has 12 threads which makes it possible to do more and deeper play outs (use threads) and fast RN performance. 

If you want to focus on play outs go for hardware acceleration (e.g. CUDA or Opencl). This method is much harder to implement and requires a strong GPU and a little less strong CPU. Any GPU would do, but if you want to use CUDA (which performs better than Opencl) go for an NVIDIA GPU. In the end the GPU approach will make Ray much stronger than the CPU only Ray. If your interested, have a look at the Leela project, they use Opencl.

I don't know how much memory Ray uses but I think you are good with any RAM. I think decent performance is already gained with the L1, L2 and L3 cache in your CPU. If you want to improve performance of deep recursive play outs (on CPU) I suggest fast RAM (e.g. DDR4 with at least 2133MHZ).

I hope this helps. :)

**Comment by zakki** [comment]
## For user
NVIDIA GPU is almost essential. Without GPU, Rn is ~x20 slow, and it's bit stronger than gnugo.

And GTX 1080 or TITAN Xp can evaluate DCNN that are requested from 4 or 8 CPU cores.
With 28 cores CPU, almost CPU core stall because of GPU bottleneck.

To think 15 seconds, Rn requires near 2GBs memory. If you need longer and deeper search, more memory is needed.

In short, i7/i9/Rythen, high end Pascal GPU (or later) and enough memory.

## For developer
1TB or more storage are required, if you want to train your own policy network and value network.
Multiple GPUs and CPU speedup data processing and deep learning.
