### ISSUE TITLE
does RN with strongest GPU usually win RN with normal GPU ? 

### ISSUE THREAD

**Issue by keseki** [zakki/Ray#117]
I bought gtx1080ti (7700k) for RN 
Because I've heard strongest gpu is strong than normal gpu

But I've heard from the old RN user that gtx1080ti and gtx1060 is not that different in updated version of RN 

What is the true?  please let me know :)

**Comment by zakki** [comment]
Perhaps, GTX 1080Ti + Ryzen 1900X wins GTX 1060 + Ryzen 1900X, because the bottleneck is GPU.
But GTX 1080Ti + Core 2 and GTX 1060 + Core 2 are very similar strength, because bottleneck is CPU.

I don't know which is bottleneck gtx1080ti or 7700k.
If you see a lots of "EVAL QUEUE FULL", it means GPU bottleneck.
And if Z value in "Eval NN : X/Y/Z" is almost always 0, CPU is a limiting factor.

**Comment by a22063821** [comment]
Not necessarily
Parameters and versions are different
It will be the key to winning
I was a low configuration but won a lot of high configuration guys

**Comment by a22063821** [comment]
Someone recently tried 3GPU
titan xp+1080ti+1080ti
But each gpu usage is only  40%

**Comment by city04** [comment]
I am the same.
Versions 4.61 and 4.20 have different computational capabilities for 1080ti and 1060 hardware.
However, when 1080ti and 1060 are confronted, the winning rates are similar.

**Comment by city04** [comment]
I am the same.
Versions 4.61 and 4.20 have different computational capabilities for 1080ti and 1060 hardware.
However, when 1080ti and 1060 confront each other, the winners are similar.

**Comment by zakki** [comment]
Roughly speaking, even if GPU was only bottleneck point, 4 times faster GPU is needed to get 1d strong.

**Comment by city04** [comment]
Until version 4.9, the stronger the hardware, the better the game odds.

I have 1050, 1060, 1070, 1080ti all.
1080ti + 1060 is inevitable because the case is small.

Problems were discovered with versions 4.61 and 4.20.

In the latter part of the game, there is a case in which the game is played without any meaning in the area of the game which is already alive.

In the latter half of the game, there is also a case where the game is played in a boundary portion where there is no meaning other than the game itself and the opponent's game.

If you win the opponent's hemp, even if the odds increase dramatically, it may happen that the situation is disadvantageous because you do not shoot and do not shoot at another place.

So the odds are worse than the 4.9 version.

Maybe we will add more gpu functionality to version 4.9 and add more proven functionality to get even better performance.
