### ISSUE TITLE
 About compiling programs under Linux?

### ISSUE THREAD

**Issue by af990m** [zakki/Ray#160]
It seems that the Makefile file is not updated and cannot be compiled under Linux.

**Comment by zakki** [comment]
CMakeFile is needed for lz branch.
I use linux only to generate self-play games on EC2, so help wanted.

**Comment by hanysz** [comment]
I think the attached makefile should work (renamed Makefile.txt because github won't let me upload a file without a filename extension!) -- I've got it to compile without errors on Ubuntu 18.04, but haven't yet had time to test.  Also you need to edit src/GoBoard.cpp : in the line that starts "inline int RevTransformMove", delete the word "inline" (or else the symbol won't be defined in GoBoard.o).
[Makefile.txt](https://github.com/zakki/Ray/files/2375242/Makefile.txt)

**Comment by zakki** [comment]
Thank you.
