### ISSUE TITLE
Oh my god jesus christ!! RN4.2 is not just "go AI". wow

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#34]
it's revolution and the origin of skynet, i think!!

oh my god, it is slaughtering all of 9D progamers. holly shit!!

nobody cannot stop me!  oh my goodness... :D :D :D

i think it will threaten "all of human mankind" beyond the Go-board  soon... holy holy ... 

👍 👍 👍 👍 👍 👍 👍 👍 

RN 4.2 = Alphago 🥇  >>>>>>>>>>>>>> Deepzengo=Fineart 👎👎 👎

**Comment by kostya** [comment]
is it play on kgs?

**Comment by zakki** [comment]
No. I'm using CGoS.
http://www.yss-aya.com/cgos/19x19/standings.html

Hong Lu's bot on DGS http://www.dragongoserver.net/userinfo.php?uid=97868
Razza99's bot on OGS https://online-go.com/player/434144/

**Comment by kyotosato** [comment]
I am new to this thread. I have some questions,

To craytok:
1. did you save your (assumed) sgf files Rayon(RN4.2) against 9 dan professionals or Rayon(RN4.2) against Zen6?
2. Employing Zen6, I have played in yahoo.jp, where a lot of (almost all Japanese) players over 5 dan amateurs and a few 2 dan (or over) professionals play there, I have almost 300 game sgf's to be examined between zen6 vs. human. Zen6 is between 2dan pro and 7 dan ama. 
note: my Zen6 setting is 30 seconds toward amateurs 5-7 dans, and 120 second/per move toward 2 dans professionals. Won 100%. Hardware: Platinum 4 Dual core, Software: windows XP. 

To zakki:
1. I appreciate your hard work regarding the new release RN 4.2. unluckily, I cannot use your 64 bit release binary because I have no 64 bit computer (hardware and software.) Mind I ask if you can release 32 bit binary, or is it a 64 bit oriented/targeted source code?
2. If RN 4.2 can be built under cygwin 32 bit? I have successfully rebuilt pachi and fuego latest version under cygwin 32 bit (cygwin 2.87 for windows XP.)
 
My intention is to test RN 4.2 by employing RN4.2 against players in yahoo.jp, KGS and www.foxwq.com, I have registered myself as 3 dan amateur. But in foxwq.com I employed Zen6 to boost my rank up to 5 dan amateur. I tested pachi and fuego latest version, both are relatively weak (maybe both are >= 1 dan amateur, even with 6 dan opening database book.dat.)  I also have tested Silver Star v.17, and leela latest release, both are weaker than Zen6. I myself is 1 ~2 dan amateur, BTW I used to be an AI researcher, and a programmer targeting Neural Network, genetic algorithm, and simulated annealing. Now I am an amateur/retired researcher in AI.

Your response is greatly appreciated.

**Comment by zakki** [comment]
Rn.4.2-4c beats Zen-11.4n-1c http://www.yss-aya.com/cgos/19x19/cross/Rn.4.2-4c.html

CUDA and CNTK doesn't support both 32bit OS and Cygwin.
Perhaps you need to implement DCNN evaluation.

I don't have any plan to support 32bit Windows.
Because Rn requires multi core CPU, over 1~2GB of free memory and high-end nvidia GPU, Rn may be weaker than Ray on poor hardware.
