### ISSUE TITLE
Playout speed will affect the chess force?

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#65]
old Rn version playout speed : 3970 po/sec 
new Rn version playout speed : 2165 po/sec
same setting
Will this affect chess?

**Comment by zakki** [comment]
Maybe yes.
It depends what is new and old.

4.x 's playout is bit slower than 3.x to check false eye and seki more strict.
I think advantage is bigger than disadvantage for this.

Bigger slow down may occur with fast CPU or slow GPU, because 4.x larger DCNN evaluation is heavy.
In this case , CPU search threads wait for GPU evaluation, and Rn outputs "EVAL QUEUE FULL" to console.

**Comment by a22063821** [comment]
I opened a mess file
Old rn of the playout speed per second is very high
new rn of the playout speed per second is very low
Let them play against each other
Old rn can reverse athe game
After I exchange the computer color and use the same archive
New rn can not reverse the game
I have tried the same three times

**Comment by a22063821** [comment]
Although the new version check to the eye and other things more strict
But the effect does not seem to the good

**Comment by zakki** [comment]
https://github.com/zakki/Ray/issues/44
