### ISSUE TITLE
How about using both of VNs of older and newer?

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#71]
Recently, I tried to make ray use older value network and newer value network at the same time.
I think it's more stable than using only new value network, but some tuning may be needed.

An average of two values are used as a value.
I suggest @zakki to consider this method.

**Comment by zakki** [comment]
I agree that ensemble tend to be good idea.
Isn't is too slow?

**Comment by wpstmxhs** [comment]
@zakki 

In my PC(Ryzen 1800X + GeForce GTX 1070), the playout speed was not slower than before(with 4 threads).
With more threads, it may slow down the playout speed.

I did some tests. I played some games on Tygem 8D~9D with it.
That ray seems good at winning stable, but sometimes it did miss some life and death on severe battle(1 game).

I also played against another ray, which my ray cannot win against (his PC is way better than mine).
It was first time that my ray resisted well. (But eventually my ray lost.)
I think ensemble gives some advantage.

**Comment by wpstmehs** [comment]
@zakki  Do not believe this fucking guy -> wpstmxhs.. hahaha  He just feeds off of his own pride.  he disrespect you zakki. he is making a fool of you. Come to DCinside Baduk Gallery. and take a look with Google Translator(Kor->Jap). He is taking a poop all the day at the gallery community and sneer you and leela developer and  all the time... He said "RN is suck program so that I don't use Rn. Leela is stronger than RN so I use leela. RN has too lots of bugs and it requires high computer specifications."  He always act like a programmer. But there is nothing that he has achieved so far. Did he referred RN Analyze mode? But did he opened it to you? All of his behaviors are just fake for showing off himself hahaha.

**Comment by wpstmxhs** [comment]
The same crazy person does this again.
I reported him to GitHub Team.

**Comment by wpstmxhs** [comment]
@zakki 

In the near future, I'll run test of ensemble on CGOS.
If it's good enough, I'll report about it.
