### ISSUE TITLE
My thoughts about strengthening Rn

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#79]
1. It seems most of commercial Go engines are using two policy networks. 
One of them is heavy policy network, which Rn also uses. and the other one is light policy network, which is fast and inaccurate.
I think we should train fast policy network to reduce the latency of GPU evaluation.
It should be nice to evaluate fast policy network in CPU.

2. It seems Monte Carlo playout is not accurate so much.
However, commercial Go engines' pure playout seems so good.
I think we should upgrade the Move Rating, or implement MM pattern matching.
Random simulation is important.

**Comment by zakki** [comment]
>  implement MM pattern matching.

Rating.cpp does that.

> It seems Monte Carlo playout is not accurate so much.
> Random simulation is important.

Yes. You will find many poor move with `ray --sim-move`.
It's easy to say, but hard to improve playout policy without slow down it.
PR welcome.

**Comment by wpstmxhs** [comment]
@zakki 

I meant MM (Minorization-Maximization) Pattern Learning. It's lightweight, but way faster than Deep Learning. Zen5, CrazyStone (including DL ver) seems using it for fast rollouts.

More detail speaking, with CPU 1 thread, It takes only 15ms per 100 evaluations.

**Comment by zakki** [comment]
The parameters in `Ray/sim_params/` are exactly what you say.
They were modeled by Remi Coulom's Bradley-Terry model, and they were calculated by MM algorithm.

**Comment by wpstmxhs** [comment]
@zakki 

I see. I'll try to improve it. Thanks.

**Comment by Mewfeuille** [comment]
> It seems Monte Carlo playout is not accurate so much.
I wonder is it possible for a go engine to remove Monte Carlo and rely on its network only, maybe Monte Carlo is the source of instability.
If the network has done large amount of training, it should be good enough to decide epic moves like what alphago does. The winrate may be more accurate if the engine knows where a good move is.
For example, AI has made a move which is good enough even for top players, but he will not think that move makes the game easier. because for his opponent, there maybe two or one certain moves that is as good as his last move, so there won't be a winrate raise because AI only take that certain moves into account. For AI, that is easy and obvious but that's top tier moves actually.

**Comment by Mewfeuille** [comment]
> It seems Monte Carlo playout is not accurate so much.


I wonder is it possible for a go engine to remove Monte Carlo and rely on its network only, maybe Monte Carlo is the source of instability.

If the network has done large amount of training, it should be good enough to decide epic moves like what alphago does. The winrate may be more accurate if the engine knows where a good move is.

For example, AI has made a move which is good enough even for top players, but he will not think that move makes the game easier. because for his opponent, there maybe two or one certain moves that is as good as his last move, so there won't be a winrate raise because AI only take that certain moves into account. For AI, that is easy and obvious but that's top tier moves actually.

**Comment by wpstmxhs** [comment]
@Mewfeuille 

It's possible. actually, someone already did it.

[http://524.teacup.com/yss/bbs?page=2&&TEACUPRBBS=23f446644612d1c810a592d1743cd5f2](http://524.teacup.com/yss/bbs?page=2&&TEACUPRBBS=23f446644612d1c810a592d1743cd5f2)
> minimax 探索囲碁プログラム  投稿者：HiraBot  投稿日：2017年 5月19日(金)14時09分35秒

But it seems pretty weak.
I think it makes sense only when policy/value network is near complete(like AlphaGo).
Since DCNN does not understand life and death, semeai, 
Well-designed Monte Carlo playouts or reinforcement learning should be needed.

**Comment by zakki** [comment]
You can try it by setting `scale = 0.99;`, or by modifying`value_scale`.
https://github.com/zakki/Ray/blob/nn/src/UctSearch.h#L65
https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L1824

**Comment by wpstmxhs** [comment]
@zakki 

I made some fix.

1) Adjusted EXPAND_THRESHOLD_19 value to 40
2) Restricted random simulation positions (allowed only if position rate >= max rate / 5)

It seems okay and quite strong simulations.
I will test it on CGOS under the name 'Rn.NewMC-16c1g'.
